# Generated by Django 4.2.3 on 2023-07-28 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaData',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('area_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('user_status', models.IntegerField(choices=[(1, 'shop'), (2, 'customer')])),
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_code', models.CharField(max_length=16)),
                ('customer_name', models.CharField(max_length=256)),
                ('customer_post_code', models.CharField(max_length=5)),
                ('customer_province', models.CharField(max_length=256)),
                ('customer_district', models.CharField(max_length=256)),
                ('customer_subdistrict', models.CharField(max_length=256)),
                ('customer_detail_address', models.CharField(max_length=256)),
                ('customer_tel', models.CharField(max_length=10)),
                ('customer_fax', models.CharField(max_length=10)),
                ('customer_email', models.CharField(max_length=64)),
                ('customer_remark', models.TextField(default='-')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DBCounter',
            fields=[
                ('counter_type', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('counter_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_code', models.CharField(max_length=16, null=True, unique=True)),
                ('product_name', models.CharField(max_length=256)),
                ('unit_cost', models.FloatField()),
                ('product_desc', models.TextField(default='-')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypeData',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type_code', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TempInputDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=16)),
                ('invoice_no', models.CharField(max_length=16)),
                ('product', models.CharField(max_length=16)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TempOutputDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=16)),
                ('invoice_no', models.CharField(max_length=16)),
                ('product', models.CharField(max_length=16)),
                ('quantity', models.IntegerField()),
                ('sale_price', models.FloatField()),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopData',
            fields=[
                ('user_status', models.IntegerField(choices=[(1, 'shop'), (2, 'customer')])),
                ('shop_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('shop_code', models.CharField(max_length=16, null=True, unique=True)),
                ('shop_name', models.CharField(max_length=128)),
                ('shop_product_type', models.CharField(max_length=32)),
                ('shop_contact', models.CharField(max_length=64)),
                ('shop_post_code', models.CharField(max_length=5)),
                ('shop_province', models.CharField(max_length=256)),
                ('shop_district', models.CharField(max_length=256)),
                ('shop_subdistrict', models.CharField(max_length=256)),
                ('shop_detail_address', models.CharField(max_length=256)),
                ('shop_tel', models.CharField(max_length=10)),
                ('shop_fax', models.CharField(max_length=10)),
                ('shop_email', models.CharField(max_length=64)),
                ('shop_remark', models.TextField(default='-')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('shop_area_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.areadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=16)),
                ('del_unit', models.IntegerField()),
                ('del_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.productdata')),
            ],
        ),
        migrations.CreateModel(
            name='OutputInvoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('invoice_no', models.CharField(max_length=16, null=True, unique=True)),
                ('total_price', models.FloatField()),
                ('discount', models.FloatField()),
                ('remark', models.TextField(default='-')),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.customerdata')),
            ],
        ),
        migrations.CreateModel(
            name='OutputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=16, null=True)),
                ('quantity', models.IntegerField()),
                ('sale_price', models.FloatField()),
                ('discount', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.outputinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.productdata')),
            ],
        ),
        migrations.CreateModel(
            name='InputInvoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('invoice_no', models.CharField(max_length=16, null=True, unique=True)),
                ('total_price', models.FloatField()),
                ('discount', models.FloatField()),
                ('remark', models.TextField(default='-')),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.shopdata')),
            ],
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=16, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('discount', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.inputinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.productdata')),
            ],
        ),
        migrations.CreateModel(
            name='DBDateCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_number', models.IntegerField()),
                ('counter_date', models.DateTimeField(auto_now_add=True)),
                ('counter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.dbcounter')),
            ],
        ),
    ]
