# Generated by Django 4.2.3 on 2023-08-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_producttypedata_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdata',
            name='shop_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopdata',
            name='shop_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
