# Generated by Django 4.2.3 on 2023-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_productdata_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='product_unit',
            field=models.IntegerField(default=1),
        ),
    ]
